### ISSUE TITLE
Add an example of how to use it

### ISSUE THREAD

**Issue by SinanBaymammadli** [jaredLunde/snowpack-plugin-mdx#1]
As title suggest it would be awesome to have example in the docs to how to use it

**Comment by jaredLunde** [comment]
The readme covers it. It's just a plugin w/ some options. What context are you missing?

**Comment by SinanBaymammadli** [comment]
I had to setup babel for it to work, made 2 examples for react and preact 
Preact: https://github.com/SinanBaymammadli/snowpack-mdx-preact-example
React: https://github.com/SinanBaymammadli/snowpack-mdx-react-example
Leaving it here if anyone needs it in the future
